"""
Seed data for the course catalogue and demo blog posts.

Run with: flask seed-courses

Safe to re-run - existing rows (matched by slug) are updated rather
than duplicated.
"""
from app.extensions import db
from app.models import Course, BlogPost

COURSES = [
    # ---------------------- TECHNOLOGY ----------------------
    dict(slug="python-programming", title="Python Programming", category="technology",
         image="courses/python.jpg",
         short_description="Learn to code with Python - the world's most beginner-friendly and in-demand programming language.",
         overview="This course introduces learners to programming fundamentals using Python, one of the most widely used languages in AI, data science and web development.",
         who_its_for="Beginners aged 10+ who want a strong foundation in programming logic.",
         age_range="10+ years", level="Beginner", duration="8 weeks", mode="Online & Physical",
         price="\u20a635,000",
         curriculum="Programming Foundations\nControl Flow\nFunctions & Data Structures\nMini Projects",
         outcomes="Write and debug Python programs independently\nUnderstand core programming logic\nComplete a personal capstone project",
         is_featured=True),
    dict(slug="artificial-intelligence", title="Artificial Intelligence", category="technology",
         image="courses/ai.jpg",
         short_description="An introduction to AI concepts, machine learning basics and practical AI tools.",
         overview="Learners explore what artificial intelligence is, how it works, and how to responsibly use and build simple AI-powered tools and projects.",
         who_its_for="Teens and adults curious about how AI works and how to build with it.",
         age_range="13+ years", level="Beginner", duration="6 weeks", mode="Online & Physical",
         price="\u20a640,000",
         curriculum="What is AI?\nWorking with AI Tools\nBasic Machine Learning Ideas\nCapstone Project",
         outcomes="Explain how AI and machine learning work\nUse AI tools responsibly\nBuild a simple AI-assisted project",
         is_featured=True),
    dict(slug="web-development", title="Web Development", category="technology",
         image="courses/webdev.jpg",
         short_description="Design and build modern, responsive websites using HTML, CSS and JavaScript.",
         overview="A practical course covering how the web works and how to design and build real websites from scratch, ending with a personal portfolio project.",
         who_its_for="Teens and adults who want to build websites and understand how the internet works.",
         age_range="13+ years", level="Beginner", duration="10 weeks", mode="Online & Physical",
         price="\u20a645,000",
         curriculum="HTML & Structure\nCSS & Styling\nJavaScript Basics\nPortfolio Project",
         outcomes="Build responsive websites from scratch\nPublish a personal portfolio website",
         is_featured=True),
    dict(slug="html-css", title="HTML & CSS", category="technology",
         image="courses/html-css.gif",
         short_description="Master the building blocks of every website - structure and style.",
         overview="A focused course on HTML and CSS for learners who want to understand how web pages are structured and styled.",
         who_its_for="Beginners aged 12+ starting their web development journey.",
         age_range="12+ years", level="Beginner", duration="4 weeks", mode="Online & Physical",
         price="\u20a625,000",
         curriculum="HTML Fundamentals\nCSS Styling",
         outcomes="Structure and style a complete web page\nPrepare for the full Web Development course"),
    dict(slug="javascript", title="JavaScript", category="technology",
         image="courses/javascript.jpg",
         short_description="Bring websites to life with interactivity, logic and dynamic behaviour.",
         overview="Learners deepen their web development skills by mastering JavaScript.",
         who_its_for="Learners who already understand HTML & CSS basics.",
         age_range="13+ years", level="Intermediate", duration="8 weeks", mode="Online & Physical",
         price="\u20a640,000",
         curriculum="JavaScript Fundamentals\nDOM & Events\nMini Web Apps",
         outcomes="Add interactivity to any website\nUnderstand modern JavaScript fundamentals"),
    dict(slug="robotics", title="Robotics", category="technology",
         image="courses/robotics.webp",
         short_description="Hands-on robotics and STEM learning - build, program and control real devices.",
         overview="An engaging, hands-on introduction to robotics and STEM principles.",
         who_its_for="Curious young learners who enjoy building and experimenting.",
         age_range="10-16 years", level="Beginner", duration="8 weeks", mode="Physical",
         price="\u20a645,000",
         curriculum="Robotics Basics\nProgramming Robots\nBuild Challenges",
         outcomes="Understand basic robotics and STEM concepts\nBuild and program a simple robot",
         is_featured=True),
    dict(slug="game-development", title="Game Development", category="technology",
         image="courses/game-dev.jpg",
         short_description="Design and build simple, fun games while learning core programming concepts.",
         overview="Learners design and build their own simple games, learning logic, creativity and programming fundamentals.",
         who_its_for="Young learners who love games and want to learn how they're made.",
         age_range="10-16 years", level="Beginner", duration="8 weeks", mode="Online & Physical",
         price="\u20a640,000",
         curriculum="Game Design Basics\nBuilding Your Game\nTesting & Showcase",
         outcomes="Design and build a playable simple game"),
    dict(slug="graphics-design", title="Graphics Design", category="technology",
         image="courses/graphics-design.jpg",
         short_description="Learn digital design principles and create professional graphics and visuals.",
         overview="A creative course covering design fundamentals, color theory, layout and practical use of modern design tools.",
         who_its_for="Teens and adults interested in creative digital work.",
         age_range="13+ years", level="Beginner", duration="6 weeks", mode="Online & Physical",
         price="\u20a635,000",
         curriculum="Design Fundamentals\nDigital Design Tools\nPortfolio Project",
         outcomes="Create professional digital graphics\nBuild a small design portfolio"),
    dict(slug="ai-content-creation", title="AI Content Creation", category="technology",
         image="courses/ai-content.jpg",
         short_description="Use AI tools to research, write, design and produce high-quality content.",
         overview="Learners discover how to responsibly use AI tools to speed up research, writing, design and content production.",
         who_its_for="Teens and adults who want to work smarter with AI content tools.",
         age_range="14+ years", level="Beginner", duration="4 weeks", mode="Online & Physical",
         price="\u20a630,000",
         curriculum="AI Content Tools Overview\nPractical Workflows\nEditing & Originality",
         outcomes="Use AI tools efficiently and responsibly\nProduce polished, original content faster"),
    dict(slug="ai-chatbot-development", title="AI Chatbot Development", category="technology",
         image="courses/chatbot.jpg",
         short_description="Design and build your own simple AI-powered chatbot.",
         overview="A hands-on introduction to how chatbots work and how to design and build a simple conversational AI chatbot.",
         who_its_for="Teens and adults interested in conversational AI and automation.",
         age_range="13+ years", level="Intermediate", duration="6 weeks", mode="Online & Physical",
         price="\u20a645,000",
         curriculum="How Chatbots Work\nBuilding the Chatbot\nTesting & Refining",
         outcomes="Design a conversational flow\nBuild and demo a working simple chatbot"),
    dict(slug="digital-skills", title="Digital Skills", category="technology",
         image="courses/digital-skills.jpg",
         short_description="Essential computer literacy and productivity skills for school, work and life.",
         overview="A practical foundation course covering computer literacy, internet safety, and Microsoft Word, Excel and PowerPoint.",
         who_its_for="Learners of all ages who want strong foundational computer skills.",
         age_range="10+ years", level="Beginner", duration="6 weeks", mode="Online & Physical",
         price="\u20a625,000",
         curriculum="Computer Literacy\nMicrosoft Word & PowerPoint\nMicrosoft Excel Basics",
         outcomes="Navigate a computer confidently\nUse Word, Excel and PowerPoint for everyday tasks"),
    dict(slug="Financial Education", title="Financial Education", category="technology",
             image="courses/finance.jpg",
             short_description="Learn essential financial tech-skills for making smart money decisions and building a strong financial future.",
             overview="A practical financial education course covering money management, budgeting, saving, investing, and responsible financial decision-making.",
             who_its_for="Students, young people, and beginers who want to understand money and develop strong financial habits.",
             age_range="All ages", level="All Levels", duration="4 weeks", mode="Online & Physical",
             price="\u20a625,000",
             curriculum="Financial Literacy\nBudgeting & Money Management\nSaving and Goal Setting\nIntroduction to Investing\nUnderstanding Income and Expenses\nSmart Financial Decision-Making.",
             outcomes="Create and manage a personal budget\nDevelop effective saving habits\nUnderstand basic investment cncepts\nMake smarter financia decisions"),
    dict(slug="data-analytics-visualization", title="Data Analytics & Visualization", category="technology",
         image="courses/data-analytic.jpg",
         short_description="Learn how to collect, analyze, visualize, and communicate data to support better decisions.",
         overview="A practical data analytics course covering data cleaning, analysis, visualization, dashboards, and essential analytical tools.",
         who_its_for="Students, beginners, professionals, and anyone interested in learning how to work with data and create meaningful insights.",
         age_range="13+ years",
         level="Beginner",
         duration="8 weeks",
         mode="Online & Physical",
         price="\u20a634,999",
         curriculum= "Introduction to Data Analytics\nUnderstanding Data Types and Datasets\nExcel for Data Analysis\nData Cleaning and Preparation\nIntroduction to Python for Data Analysis\nPandas and NumPy Basics\nData Visualization with Matplotlib\nCreating Charts and Interactive Dashboards\nIntroduction to Power BI\nData Storytelling and Presenting Insights\nPractical Data Analytics Projects",
         outcomes="Learners will be able to clean, analyze, visualize, and interpret data and present meaningful insights using modern data analytics tools."),
    
    dict(slug="cybersecurity", title="Cybersecurity", category="technology",
          image="courses/cybersecurity.jpg",
          short_description="Learn how to protect devices, information, accounts, and digital systems from common cyber threats.",
          overview="A practical cybersecurity course covering online safety, cyber threats, password security, phishing, data protection, and ethical cybersecurity practices.",
          who_its_for="Students, beginners, professionals, and anyone interested in understanding cybersecurity and staying safe in the digital world.",
          age_range="13+ years",
          level="Beginner",
          duration="8 weeks",
          mode="Online & Physical",
          price="\u20a634,999",
          curriculum="Introduction to Cybersecurity\nUnderstanding Cyber Threats\nMalware, Viruses, and Ransomware\nPhishing and Social Engineering\nPassword and Account Security\nInternet and Network Security Basics\nSafe Browsing and Email Security\nData Privacy and Protection\nIntroduction to Ethical Hacking\nCybersecurity Tools and Best Practices\nPractical Cybersecurity Projects",
          outcomes="Learners will understand common cybersecurity threats, apply safe digital practices, identify suspicious activities, and understand the fundamentals of protecting digital information."),
    
    dict(slug="digital-marketing", title="Digital Marketing", category="technology",
          image="courses/digital-marketing.jpg",
          short_description="Learn how to promote businesses, products, and services using social media, content, search, and digital advertising.",
          overview="A practical digital marketing course covering social media marketing, content creation, branding, search engine optimization, online advertising, analytics, and digital marketing strategy.",
          who_its_for="Students, beginners, entrepreneurs, business owners, creators, and anyone interested in developing practical digital marketing skills.",
          age_range="13+ years",
          level="Beginner",
          duration="8 weeks",
          mode="Online & Physical",
          price="\u20a634,999",
          curriculum="Introduction to Digital Marketing\nUnderstanding Digital Audiences\nBranding and Online Presence\nContent Marketing\nSocial Media Marketing\nFacebook and Instagram Marketing\nIntroduction to Search Engine Optimization\nEmail Marketing Basics\nDigital Advertising Fundamentals\nUnderstanding Marketing Analytics\nBuilding a Digital Marketing Campaign\nPractical Digital Marketing Project",
          outcomes="Learners will be able to develop digital marketing strategies, create engaging content, manage social media campaigns, understand online advertising, and measure marketing performance."),
     
     dict(slug="scratch-programming", title="Scratch Programming", category="technology",
          image="courses/scratch.jpg",
          short_description="Learn programming concepts by creating fun games, animations, stories, and interactive projects with Scratch.",
          overview="A fun and practical introduction to programming for young learners using Scratch's visual programming environment to build creative games, animations, stories, and interactive applications.",
          who_its_for="Children and young learners who want to develop programming, problem-solving, creativity, and computational thinking skills.",
          age_range="7-12 years",
          level="Beginner",
          duration="6 weeks",
          mode="Online & Physical",
          price="\u20a624,999",
          curriculum="Introduction to Programming\nGetting Started with Scratch\nSprites, Backdrops, and Costumes\nMotion and Looks Blocks\nEvents and Controls\nLoops and Repetition\nVariables and Scoring\nConditions and Decision Making\nSounds and Animations\nCreating Interactive Games\nBuilding Stories and Animations\nFinal Scratch Programming Project",
          outcomes="Learners will understand basic programming concepts and be able to create interactive games, animations, stories, and simple projects using Scratch."),
     

    # ---------------------- ACADEMIC ----------------------
    dict(slug="mathematics", title="Mathematics", category="academic",
         image="courses/mathematics.jpg",
         short_description="Personalised support to strengthen mathematics understanding and confidence.",
         overview="Structured mathematics tutoring aligned with the learner's curriculum.",
         who_its_for="Primary, secondary and pre-university students needing math support.",
         age_range="6-18 years", level="All Levels", duration="Flexible / ongoing", mode="Online & Physical",
         price="Contact for pricing",
         curriculum="Diagnostic Assessment\nGuided Practice\nExam-Style Practice",
         outcomes="Improved confidence and grades in mathematics"),
    dict(slug="english", title="English", category="academic",
         image="courses/english.jpg",
         short_description="Strengthen reading, writing, grammar and comprehension skills.",
         overview="Comprehensive English language support covering grammar, comprehension, essay writing and communication skills.",
         who_its_for="Primary, secondary and pre-university students.",
         age_range="6-18 years", level="All Levels", duration="Flexible / ongoing", mode="Online & Physical",
         price="Contact for pricing",
         curriculum="Grammar & Structure\nComprehension & Vocabulary\nEssay & Composition Writing",
         outcomes="Improved writing and comprehension skills"),
    dict(slug="science", title="Science", category="academic",
         image="courses/science.jpg",
         short_description="Support across core science subjects with clear, practical explanations.",
         overview="Tutoring across core science subjects, helping learners understand key concepts.",
         who_its_for="Primary and secondary students studying core sciences.",
         age_range="9-18 years", level="All Levels", duration="Flexible / ongoing", mode="Online & Physical",
         price="Contact for pricing",
         curriculum="Core Concepts\nApplied Learning\nRevision & Practice",
         outcomes="Stronger grasp of core scientific concepts"),
    dict(slug="general-academic-support", title="General Academic Support", category="academic",
         image="courses/academic-support.jpg",
         short_description="Well-rounded academic mentoring across multiple subjects.",
         overview="A flexible academic support programme covering multiple subjects, study skills and consistent mentoring.",
         who_its_for="Students who need general academic guidance across subjects.",
         age_range="6-18 years", level="All Levels", duration="Flexible / ongoing", mode="Online & Physical",
         price="Contact for pricing",
         curriculum="Study Skills\nSubject Support",
         outcomes="Improved study habits\nStronger overall academic performance"),
    dict(slug="homework-support", title="Homework Support", category="academic",
         image="courses/homework-support.jpg",
         short_description="Guided daily/weekly homework help to keep learners on track.",
         overview="Structured homework support sessions that help learners complete assignments correctly.",
         who_its_for="Learners who need consistent, guided homework assistance.",
         age_range="6-16 years", level="All Levels", duration="Flexible / ongoing", mode="Online & Physical",
         price="Contact for pricing",
         curriculum="Guided Homework Sessions",
         outcomes="Consistent, on-time homework completion"),

    # ---------------------- EXAM PREP ----------------------
    dict(slug="waec/neco/jamb-preparation", title="WAEC/NECO/JAMB Preparation", category="exam-prep",
         image="courses/waec.jpg",
         short_description="Focused, structured preparation for the WAEC/NECO/JAMB examinations.",
         overview="An intensive preparation programme covering core WAEC/NECO/JAMB subjects, past questions, timed practice and exam techniques.",
         who_its_for="Senior secondary students preparing for WAEC,NECO and JAMB.",
         age_range="15-18 years", level="Intermediate", duration="12 weeks", mode="Online & Physical",
         price="Contact for pricing",
         curriculum="Syllabus Review\nPast Questions\nMock Examinations",
         outcomes="Improved readiness and confidence for WAEC, NECO and JAMB", is_featured=True),
    
    dict(slug="cambridge-preparation", title="Cambridge Examination Preparation", category="exam-prep",
         image="courses/cambridge.jpg",
         short_description="Support for learners preparing for Cambridge assessments (IGCSE and related exams).",
         overview="Structured academic support aligned with the Cambridge curriculum.",
         who_its_for="Students enrolled in Cambridge-curriculum schools.",
         age_range="11-18 years", level="All Levels", duration="Flexible / ongoing", mode="Online & Physical",
         price="Contact for pricing",
         curriculum="Curriculum Review\nPast Paper Practice",
         outcomes="Stronger command of Cambridge syllabus content"),
    # ---------------------- LANGUAGES ----------------------
    dict(slug="language-courses", title="Language Courses", category="languages",
         image="courses/languages.jpg",
         short_description="Language learning support for learners of all ages and levels.",
         overview="Dynamic Academy supports language learning for students who want to build fluency and confidence.",
         who_its_for="Learners of all ages interested in developing language skills.",
         age_range="All ages", level="All Levels", duration="Flexible", mode="Online & Physical",
         price="Contact for pricing",
         curriculum="Custom Language Plan",
         outcomes="Improved fluency and confidence in the target language"),
]

BLOG_POSTS = [
    dict(slug="why-kids-should-learn-to-code-early", title="Why Kids Should Learn to Code Early",
         excerpt="Coding builds problem-solving skills that go far beyond the screen.",
         content="This is demo content - replace with a real article before launch.\n\nLearning to code early helps children develop logical thinking, patience and creativity.",
         category="Coding", image="blog/coding-early.jpg"),
    dict(slug="how-ai-is-changing-education", title="How AI Is Changing Education",
         excerpt="Artificial intelligence is reshaping how students learn.",
         content="This is demo content - replace with a real article before launch.\n\nFrom personalised learning tools to AI-assisted research, AI is becoming part of everyday education.",
         category="AI", image="blog/ai-education.jpg"),
    dict(slug="preparing-for-waec-neco-jamb", title="A Practical Guide to Preparing for WAEC, NECO & JAMB",
         excerpt="Practical strategies that actually help students perform better.",
         content="This is demo content - replace with a real article before launch.\n\nConsistent revision, past-question practice and timed mock exams are among the most effective strategies.",
         category="Education", image="blog/exam-prep.jpg"),
]


def seed_all():
    for data in COURSES:
        existing = Course.query.filter_by(slug=data["slug"]).first()
        if existing:
            for key, value in data.items():
                setattr(existing, key, value)
        else:
            db.session.add(Course(**data))

    for data in BLOG_POSTS:
        existing = BlogPost.query.filter_by(slug=data["slug"]).first()
        if existing:
            for key, value in data.items():
                setattr(existing, key, value)
        else:
            db.session.add(BlogPost(**data))

    db.session.commit()
